name: Lint
on: [push]
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  lint:
    name: Lint suite
    runs-on: ubuntu-latest
    container: meterup/ubuntu-golang
    steps:
      - uses: actions/checkout@v2
      - run: go vet ./...
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          only-new-issues: true
    timeout-minutes: 10
